In [4]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

In [5]:
X,y = load_diabetes(return_X_y=True)

In [6]:
X_train ,X_test, y_train, y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [ ]:
# lambda(in equation) = alpha
reg = Ridge(alpha=0.1,solver='cholesky')

In [33]:
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)  
r2_score(y_test,y_pred)

0.46085219464119254

In [9]:
reg.coef_,reg.intercept_

(array([  42.85566976, -205.49431899,  505.08903304,  317.0932049 ,
        -108.50026183,  -86.23673333, -190.36318008,  151.70708637,
         392.28931896,   79.9081772 ]),
 np.float64(151.4585745667961))

In [26]:
# lambda (in equation) = alpha
class meraRidgeGD:
    def __init__(self,alpha,epochs,learning_rate):
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None
        self.epochs = epochs
        self.learning_rate = learning_rate
    
    def fit(self,X_train,y_train):
        self.coef_ = np.ones(X_train.shape[1])
        intercept = 0
        theta = np.insert(np.ones(X_train.shape[1]),0,0,intercept)

        X_train = np.insert(X_train,0,1,axis=1)

        for i in range(self.epochs):
            theta_derivative = np.dot(np.transpose(X_train),X_train).dot(theta) - np.dot(np.transpose(X_train),y_train) + self.alpha*theta
            theta = theta  - self.learning_rate * theta_derivative
        # print(theta)
        
        self.intercept_ = theta[1:]
        self.coef_ = theta[0]

        return self.coef_, self.intercept_

    def predict(self,X_test):
        
        return np.dot(X_test,self.coef_) + self.intercept_


In [27]:
ridgeGD = meraRidgeGD(epochs=500,alpha=0.001,learning_rate=0.005)

In [28]:
ridgeGD.fit(X_train,y_train)

(np.float64(151.4045475591972),
 array([  43.37183861, -192.03766574,  496.43542567,  319.37407   ,
         -64.42788084, -113.194338  , -213.9073644 ,  144.86136322,
         367.67948022,  119.56857869]))

In [29]:
y_pred = reg.predict(X_test)
print("R2 score",r2_score(y_test,y_pred))
print(reg.coef_)
print(reg.intercept_)

R2 score 0.46085219464119254
[  42.85566976 -205.49431899  505.08903304  317.0932049  -108.50026183
  -86.23673333 -190.36318008  151.70708637  392.28931896   79.9081772 ]
151.4585745667961


In [ ]:
# np.ones(X_train.shape[1])
# intercept = 0
# np.insert(np.ones(X_train.shape[1]),0,0,intercept)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# np.arange(8).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])